### ISSUE TITLE
TypeError in StripeForm component on staging

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-component-library#325]
Type: **minor**

**Describe the bug**
The `StripeForm` component is throwing a `TypeError` on the design system staging site.

**To Reproduce**
1. Visit the [StripForm](https://designsystem.reactioncommerce.com/#!/StripeForm) docs and see the error.
2. Visit the [StripePaymentCheckoutAction](https://designsystem.reactioncommerce.com/#!/StripePaymentCheckoutAction) docs and see the error.
3. Spin up the comp-lib locally, visit the above pages and see the `StripeForm` working correctly.
4. Checkout within the starterkit to see `StripeForm` working correctly.

**Expected behavior**
`StripeForm` to render without any errors.
 
**Screenshots**
![screen shot 2018-10-09 at 1 42 52 pm](https://user-images.githubusercontent.com/1135948/46690982-5cc3c900-cbc9-11e8-8adc-4e150521a863.png)

![screen shot 2018-10-09 at 1 43 09 pm](https://user-images.githubusercontent.com/1135948/46690993-61887d00-cbc9-11e8-801c-a749e3a4d74b.png)

**Additional context**
I'm guessing this is just a missing Stripe dep/lib that we need on staging.

**Comment by spencern** [comment]
@nnnnat @willopez any idea if this is a regression?

**Comment by nnnnat** [comment]
@spencern I don't think it is because it looks to be working locally and in the storefront

**Comment by aldeed** [comment]
@nnnnat In development, I have noticed some warnings related to the context. Maybe these warnings become errors in the production build? I think it might be because Stripe renders the fields within iframes, and therefore they don't seem to have access to the React context (`withTheme` provides `null` for the theme prop).

**Comment by willopez** [comment]
@aldeed I believe you are correct, the `StripeForm` component does not have access to the theme prop. However, this was working at some point, perhaps the way the theme is provided was modified.

**Comment by aldeed** [comment]
Looking at the history, this is most likely from my commit here: https://github.com/reactioncommerce/reaction-component-library/commit/1ad5d9c06042a27bff82102c28ca78170fd49cf0#diff-6450d94ec81d8b2d1ab5036e3eb413f0

Prior to that, `withTheme` wrapper was not used. However, if we don't have `withTheme` then there isn't any point in using theme variables at all because there's no way to override our default theme. That was why I added the wrapper.

It's strange that `withComponents` seems to work but not `withTheme`. It might be due to `withComponents` using the newer React context.

The simple fix for now would be to remove `withTheme` I guess, but then we're back to having a form that isn't themable.
