### ISSUE TITLE
Why Heading fontSize is smaller than SubHeading fontSize?

### ISSUE THREAD

**Issue by alexakasanjeev** [reactioncommerce/reaction-component-library#410]
Type: **minor**
This is related to the design language

**Describe the bug**
I am going through typography style, in that headingText has font size of 16 whereas subheadingText font size is 18, and it is also mention that headingText should be used as a Card title and subheadingText should be used to denote new section in card. If we follow hierarchy, card title should be bigger than the sub heading in the card.
Here is the code snippet from typography.js 

`
  headingText: {
    fontSize: "16px",
  },
  subheadingText: {
    fontSize: "18px",
  }
`

**To Reproduce**
1. Go to [typography.js](https://github.com/reactioncommerce/reaction-component-library/blob/master/package/src/theme/typography.js)

**Expected behavior**
heading Text should be 20px or atleast greater than subHeadingText

`
  headingText: {
    fontSize: "20px",
  },
  subheadingText: {
    fontSize: "18px",
  }
`

**Additional context**
This is not a bug, this question is related to design language that you have created. If there is a specific reason why headingText fontSize is smaller than subHeadingText fontSize, I would like to know

**Comment by rymorgan** [comment]
@cassytaylor Can we provide some context here?

**Comment by aldeed** [comment]
I'll leave it to Cassy to address the design aesthetics question, but from a technical perspective, all components should be using "heading" for primary heading text and "subheading" for secondary heading text and making no assumptions about which will be bigger or how big each will be. Assuming this is true, you're free to make any font size changes to the default theme. If it's not true, then you should file an issue to describe which components are incorrectly categorizing their text.

**Comment by alexakasanjeev** [comment]
@aldeed I was reading Design Language that your team has written, I really like how you have categorized typography into 6 main types:
1. Title
2. Heading
3. SubHeading
4. Body
5. Label
6. Caption

I think it really scales well and I like the approach I was just curious why, "Heading" size is smaller than "SubHeading" size, as you clearly mention "Heading" is for Primary Heading and "SubHeading" is for secondary heading, and the natural instinct is Primary Heading should be bigger than Secondary Heading. That's all.

**I don't have problem with any component being wrongly categorized**

**Comment by cassytaylor** [comment]
Hi @alexakasanjeev, the current set of type styles in our design system are all named for their usage in our v1 admin panel UI. The 'Heading' style was used for card or section titles, and the SubHeading style for sections within those cards (or sub-sections.) As for why the SubHeading style is bigger than the Heading style - I think it was for visual hierarchy (since the Heading text would normally be wrapped in a card header container with a light gray background, giving it more visual weight although it was smaller); but I'm not entirely sure why that decision was made - I just wrote the documentation for it!
However, we are currently implementing a new admin UI, and updating all of these type styles accordingly. The equivalents of the Title, Heading and SubHeading, etc. styles will cascade from biggest to smallest.

**Comment by alexakasanjeev** [comment]
@cassytaylor Thank you for the clarification, I really appreciate your time.

Also will the new admin UI you are talking about, will it be updated on this link https://designsystem.reactioncommerce.com
Because I am following this link to understand the design language that you all have created.

**Comment by rymorgan** [comment]
@alexakasanjeev Yes, that's the plan.
