### ISSUE TITLE
InPageMenu and InPageMenuItem components

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-component-library#66]
## Summary
Create InPageMenu and InPageMenuItem components in the component library

## Implementation
See designs. Just need this for the starter kit profile pages for now.

**Comment by cassytaylor** [comment]
Menu documentation (we're calling it "in-page menu" for now) is here - http://zpl.io/2poNemo

![in-page menu - guidelines](https://user-images.githubusercontent.com/36006187/37793687-9701c626-2dcc-11e8-9898-d08834d854bd.png)

**Comment by kieckhafer** [comment]
@aldeed @spencern What's the best way to pass down the Item information from the `InPageMenu` to the `InPageMenuItem(s)`.

An object containing a labels and links?

**Comment by aldeed** [comment]
@kieckhafer My thoughts:
- Use the `Link` component from `components`, which takes `href` and `onClick` props
- So yes, probably an array of objects, but maybe `href` instead of `link` to match `Link` prop.
- Also use `PropTypes.node` for `label` so it could have icons or other things in addition to text
- You could add `id` to the objects, too, and then have an `onClick` prop that gets called with the `id` of what was clicked whenever each `Link` `onClick` is called.
